name = "MC Eternal 2"
version = "1.2.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "697075f4a2d9a117e2610ea72aa68ed9630aa90bdf4c214d26de039c50b6832f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
