name = "MC Eternal 2"
version = "1.2.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc5fbc87d5ff2165ff3e1a30e6a84b6fdaceff0ae08a5b56c98721e18e1cb3ae"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
